name: DotNet CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use
    - name: Build with dotnet
      working-directory: src
      run: |
        dotnet build
    - name: Unit tests
      working-directory: src
      run: |
        dotnet test